// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protos/learning/user_progress.proto

package genprotos

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Foydalanuvchi taraqqiyotini qo'shish uchun xabar
type AddUserProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Foydalanuvchi ID'si
	LanguageId   string               `protobuf:"bytes,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`       // Tilning UUID si
	LessonId     string               `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`             // Darsning UUID si
	ExerciseId   string               `protobuf:"bytes,4,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`       // Mashqning UUID si
	VocabularyId string               `protobuf:"bytes,5,opt,name=vocabulary_id,json=vocabularyId,proto3" json:"vocabulary_id,omitempty"` // Leksika yozuvining UUID si
	CompletedAt  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`    // Tugatilgan vaqti
}

func (x *AddUserProgressRequest) Reset() {
	*x = AddUserProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_user_progress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserProgressRequest) ProtoMessage() {}

func (x *AddUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_user_progress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserProgressRequest.ProtoReflect.Descriptor instead.
func (*AddUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_user_progress_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserProgressRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *AddUserProgressRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *AddUserProgressRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *AddUserProgressRequest) GetVocabularyId() string {
	if x != nil {
		return x.VocabularyId
	}
	return ""
}

func (x *AddUserProgressRequest) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Foydalanuvchi taraqqiyotini qo'shish javobi
type AddUserProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddUserProgressResponse) Reset() {
	*x = AddUserProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_user_progress_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserProgressResponse) ProtoMessage() {}

func (x *AddUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_user_progress_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserProgressResponse.ProtoReflect.Descriptor instead.
func (*AddUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_user_progress_proto_rawDescGZIP(), []int{1}
}

// Foydalanuvchi taraqqiyotini olish uchun xabar
type GetUserProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Foydalanuvchi ID'si
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_user_progress_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_user_progress_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_user_progress_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Foydalanuvchi taraqqiyotini olish javobi
type GetUserProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserProgressList []*UserProgress `protobuf:"bytes,1,rep,name=user_progress_list,json=userProgressList,proto3" json:"user_progress_list,omitempty"` // Foydalanuvchi taraqqiyoti ro'yxati
}

func (x *GetUserProgressResponse) Reset() {
	*x = GetUserProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_user_progress_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressResponse) ProtoMessage() {}

func (x *GetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_user_progress_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_user_progress_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProgressResponse) GetUserProgressList() []*UserProgress {
	if x != nil {
		return x.UserProgressList
	}
	return nil
}

// Foydalanuvchi taraqqiyoti haqida ma'lumotni aniqlash uchun xabar
type UserProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Foydalanuvchi ID'si
	LanguageId   string               `protobuf:"bytes,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`       // Tilning UUID si
	LessonId     string               `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`             // Darsning UUID si
	ExerciseId   string               `protobuf:"bytes,4,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`       // Mashqning UUID si
	VocabularyId string               `protobuf:"bytes,5,opt,name=vocabulary_id,json=vocabularyId,proto3" json:"vocabulary_id,omitempty"` // Leksika yozuvining UUID si
	CompletedAt  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`    // Tugatilgan vaqti
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_user_progress_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_user_progress_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_protos_learning_user_progress_proto_rawDescGZIP(), []int{4}
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *UserProgress) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *UserProgress) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *UserProgress) GetVocabularyId() string {
	if x != nil {
		return x.VocabularyId
	}
	return ""
}

func (x *UserProgress) GetCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_protos_learning_user_progress_proto protoreflect.FileDescriptor

var file_protos_learning_user_progress_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x76,
	0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x19, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x67, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x12, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x32, 0xe5, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0f, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x28,
	0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x28, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_learning_user_progress_proto_rawDescOnce sync.Once
	file_protos_learning_user_progress_proto_rawDescData = file_protos_learning_user_progress_proto_rawDesc
)

func file_protos_learning_user_progress_proto_rawDescGZIP() []byte {
	file_protos_learning_user_progress_proto_rawDescOnce.Do(func() {
		file_protos_learning_user_progress_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_learning_user_progress_proto_rawDescData)
	})
	return file_protos_learning_user_progress_proto_rawDescData
}

var file_protos_learning_user_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_learning_user_progress_proto_goTypes = []any{
	(*AddUserProgressRequest)(nil),  // 0: languagelearning.AddUserProgressRequest
	(*AddUserProgressResponse)(nil), // 1: languagelearning.AddUserProgressResponse
	(*GetUserProgressRequest)(nil),  // 2: languagelearning.GetUserProgressRequest
	(*GetUserProgressResponse)(nil), // 3: languagelearning.GetUserProgressResponse
	(*UserProgress)(nil),            // 4: languagelearning.UserProgress
	(*timestamp.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_protos_learning_user_progress_proto_depIdxs = []int32{
	5, // 0: languagelearning.AddUserProgressRequest.completed_at:type_name -> google.protobuf.Timestamp
	4, // 1: languagelearning.GetUserProgressResponse.user_progress_list:type_name -> languagelearning.UserProgress
	5, // 2: languagelearning.UserProgress.completed_at:type_name -> google.protobuf.Timestamp
	0, // 3: languagelearning.UserProgressService.AddUserProgress:input_type -> languagelearning.AddUserProgressRequest
	2, // 4: languagelearning.UserProgressService.GetUserProgress:input_type -> languagelearning.GetUserProgressRequest
	1, // 5: languagelearning.UserProgressService.AddUserProgress:output_type -> languagelearning.AddUserProgressResponse
	3, // 6: languagelearning.UserProgressService.GetUserProgress:output_type -> languagelearning.GetUserProgressResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_learning_user_progress_proto_init() }
func file_protos_learning_user_progress_proto_init() {
	if File_protos_learning_user_progress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_learning_user_progress_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_user_progress_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_user_progress_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_user_progress_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_user_progress_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UserProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_learning_user_progress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_learning_user_progress_proto_goTypes,
		DependencyIndexes: file_protos_learning_user_progress_proto_depIdxs,
		MessageInfos:      file_protos_learning_user_progress_proto_msgTypes,
	}.Build()
	File_protos_learning_user_progress_proto = out.File
	file_protos_learning_user_progress_proto_rawDesc = nil
	file_protos_learning_user_progress_proto_goTypes = nil
	file_protos_learning_user_progress_proto_depIdxs = nil
}
