// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protos/learning/vocabulary.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Leksika yozuvini qo'shish uchun xabar
type AddVocabularyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LanguageCode string `protobuf:"bytes,1,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // Til kodi, masalan, 'en', 'uz'
	Word         string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`                                     // So'z
	Translation  string `protobuf:"bytes,3,opt,name=translation,proto3" json:"translation,omitempty"`                       // So'z tarjimasi
}

func (x *AddVocabularyRequest) Reset() {
	*x = AddVocabularyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVocabularyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVocabularyRequest) ProtoMessage() {}

func (x *AddVocabularyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVocabularyRequest.ProtoReflect.Descriptor instead.
func (*AddVocabularyRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{0}
}

func (x *AddVocabularyRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *AddVocabularyRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *AddVocabularyRequest) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

// Leksika yozuvini qo'shish javobi
type AddVocabularyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Yaratilgan leksika yozuving UUID si
}

func (x *AddVocabularyResponse) Reset() {
	*x = AddVocabularyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVocabularyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVocabularyResponse) ProtoMessage() {}

func (x *AddVocabularyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVocabularyResponse.ProtoReflect.Descriptor instead.
func (*AddVocabularyResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{1}
}

func (x *AddVocabularyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Leksika yozuvini olish uchun xabar
type GetVocabularyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Leksika yozuving UUID si
}

func (x *GetVocabularyRequest) Reset() {
	*x = GetVocabularyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVocabularyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocabularyRequest) ProtoMessage() {}

func (x *GetVocabularyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocabularyRequest.ProtoReflect.Descriptor instead.
func (*GetVocabularyRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{2}
}

func (x *GetVocabularyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Leksika yozuvini olish javobi
type GetVocabularyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vocabulary *Vocabulary `protobuf:"bytes,1,opt,name=vocabulary,proto3" json:"vocabulary,omitempty"` // Leksika yozuvi haqida ma'lumot
}

func (x *GetVocabularyResponse) Reset() {
	*x = GetVocabularyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVocabularyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocabularyResponse) ProtoMessage() {}

func (x *GetVocabularyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocabularyResponse.ProtoReflect.Descriptor instead.
func (*GetVocabularyResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{3}
}

func (x *GetVocabularyResponse) GetVocabulary() *Vocabulary {
	if x != nil {
		return x.Vocabulary
	}
	return nil
}

// Leksika yozuvini yangilash uchun xabar
type UpdateVocabularyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Leksika yozuving UUID si
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // Til kodi, masalan, 'en', 'uz'
	Word         string `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`                                     // So'z
	Translation  string `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`                       // So'z tarjimasi
}

func (x *UpdateVocabularyRequest) Reset() {
	*x = UpdateVocabularyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVocabularyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVocabularyRequest) ProtoMessage() {}

func (x *UpdateVocabularyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVocabularyRequest.ProtoReflect.Descriptor instead.
func (*UpdateVocabularyRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateVocabularyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVocabularyRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *UpdateVocabularyRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *UpdateVocabularyRequest) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

// Leksika yozuvini yangilash javobi
type UpdateVocabularyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vocabulary *Vocabulary `protobuf:"bytes,1,opt,name=vocabulary,proto3" json:"vocabulary,omitempty"` // Yangilangan leksika yozuvi haqida ma'lumot
}

func (x *UpdateVocabularyResponse) Reset() {
	*x = UpdateVocabularyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVocabularyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVocabularyResponse) ProtoMessage() {}

func (x *UpdateVocabularyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVocabularyResponse.ProtoReflect.Descriptor instead.
func (*UpdateVocabularyResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVocabularyResponse) GetVocabulary() *Vocabulary {
	if x != nil {
		return x.Vocabulary
	}
	return nil
}

// Leksika yozuvi o'chirish uchun xabar
type DeleteVocabularyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Leksika yozuving UUID si
}

func (x *DeleteVocabularyRequest) Reset() {
	*x = DeleteVocabularyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVocabularyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVocabularyRequest) ProtoMessage() {}

func (x *DeleteVocabularyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVocabularyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVocabularyRequest) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVocabularyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Leksika yozuvi o'chirish javobi
type DeleteVocabularyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // O'chirilgan leksika yozuving UUID si
}

func (x *DeleteVocabularyResponse) Reset() {
	*x = DeleteVocabularyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVocabularyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVocabularyResponse) ProtoMessage() {}

func (x *DeleteVocabularyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVocabularyResponse.ProtoReflect.Descriptor instead.
func (*DeleteVocabularyResponse) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVocabularyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Leksika yozuvi haqida ma'lumotni aniqlash uchun xabar
type Vocabulary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Leksika yozuving UUID si
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // Til kodi, masalan, 'en', 'uz'
	Word         string `protobuf:"bytes,3,opt,name=word,proto3" json:"word,omitempty"`                                     // So'z
	Translation  string `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`                       // So'z tarjimasi
	CreatedAt    string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // Yaratilgan vaqti
	UpdatedAt    string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // Yangilangan vaqti
}

func (x *Vocabulary) Reset() {
	*x = Vocabulary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_learning_vocabulary_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vocabulary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vocabulary) ProtoMessage() {}

func (x *Vocabulary) ProtoReflect() protoreflect.Message {
	mi := &file_protos_learning_vocabulary_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vocabulary.ProtoReflect.Descriptor instead.
func (*Vocabulary) Descriptor() ([]byte, []int) {
	return file_protos_learning_vocabulary_proto_rawDescGZIP(), []int{8}
}

func (x *Vocabulary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vocabulary) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *Vocabulary) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Vocabulary) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *Vocabulary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Vocabulary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_protos_learning_vocabulary_proto protoreflect.FileDescriptor

var file_protos_learning_vocabulary_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2f, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x71, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63, 0x61, 0x62,
	0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x56, 0x6f,
	0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x56,
	0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c,
	0x61, 0x72, 0x79, 0x52, 0x0a, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x22,
	0x84, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75,
	0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75,
	0x6c, 0x61, 0x72, 0x79, 0x52, 0x0a, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79,
	0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75,
	0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb5, 0x01, 0x0a, 0x0a, 0x56, 0x6f, 0x63, 0x61,
	0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32,
	0xad, 0x03, 0x0a, 0x11, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63, 0x61,
	0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x26, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63,
	0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x6f,
	0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x26, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x29, 0x2e,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f,
	0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x29, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x63,
	0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_learning_vocabulary_proto_rawDescOnce sync.Once
	file_protos_learning_vocabulary_proto_rawDescData = file_protos_learning_vocabulary_proto_rawDesc
)

func file_protos_learning_vocabulary_proto_rawDescGZIP() []byte {
	file_protos_learning_vocabulary_proto_rawDescOnce.Do(func() {
		file_protos_learning_vocabulary_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_learning_vocabulary_proto_rawDescData)
	})
	return file_protos_learning_vocabulary_proto_rawDescData
}

var file_protos_learning_vocabulary_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_learning_vocabulary_proto_goTypes = []any{
	(*AddVocabularyRequest)(nil),     // 0: languagelearning.AddVocabularyRequest
	(*AddVocabularyResponse)(nil),    // 1: languagelearning.AddVocabularyResponse
	(*GetVocabularyRequest)(nil),     // 2: languagelearning.GetVocabularyRequest
	(*GetVocabularyResponse)(nil),    // 3: languagelearning.GetVocabularyResponse
	(*UpdateVocabularyRequest)(nil),  // 4: languagelearning.UpdateVocabularyRequest
	(*UpdateVocabularyResponse)(nil), // 5: languagelearning.UpdateVocabularyResponse
	(*DeleteVocabularyRequest)(nil),  // 6: languagelearning.DeleteVocabularyRequest
	(*DeleteVocabularyResponse)(nil), // 7: languagelearning.DeleteVocabularyResponse
	(*Vocabulary)(nil),               // 8: languagelearning.Vocabulary
}
var file_protos_learning_vocabulary_proto_depIdxs = []int32{
	8, // 0: languagelearning.GetVocabularyResponse.vocabulary:type_name -> languagelearning.Vocabulary
	8, // 1: languagelearning.UpdateVocabularyResponse.vocabulary:type_name -> languagelearning.Vocabulary
	0, // 2: languagelearning.VocabularyService.AddVocabulary:input_type -> languagelearning.AddVocabularyRequest
	2, // 3: languagelearning.VocabularyService.GetVocabulary:input_type -> languagelearning.GetVocabularyRequest
	4, // 4: languagelearning.VocabularyService.UpdateVocabulary:input_type -> languagelearning.UpdateVocabularyRequest
	6, // 5: languagelearning.VocabularyService.DeleteVocabulary:input_type -> languagelearning.DeleteVocabularyRequest
	1, // 6: languagelearning.VocabularyService.AddVocabulary:output_type -> languagelearning.AddVocabularyResponse
	3, // 7: languagelearning.VocabularyService.GetVocabulary:output_type -> languagelearning.GetVocabularyResponse
	5, // 8: languagelearning.VocabularyService.UpdateVocabulary:output_type -> languagelearning.UpdateVocabularyResponse
	7, // 9: languagelearning.VocabularyService.DeleteVocabulary:output_type -> languagelearning.DeleteVocabularyResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_learning_vocabulary_proto_init() }
func file_protos_learning_vocabulary_proto_init() {
	if File_protos_learning_vocabulary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_learning_vocabulary_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddVocabularyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddVocabularyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetVocabularyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetVocabularyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateVocabularyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateVocabularyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteVocabularyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteVocabularyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_learning_vocabulary_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Vocabulary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_learning_vocabulary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_learning_vocabulary_proto_goTypes,
		DependencyIndexes: file_protos_learning_vocabulary_proto_depIdxs,
		MessageInfos:      file_protos_learning_vocabulary_proto_msgTypes,
	}.Build()
	File_protos_learning_vocabulary_proto = out.File
	file_protos_learning_vocabulary_proto_rawDesc = nil
	file_protos_learning_vocabulary_proto_goTypes = nil
	file_protos_learning_vocabulary_proto_depIdxs = nil
}
